swagger: "2.0"
info:
    description: "This is the jira rest resources endpoint documentation"
    version: "8.3.2"
    title: "Jira Rest Resources"
basePath: "/api/2"
tags:
    - name: jira 
    
schemes: 
    - "https"
paths:
    /issue:
        post:
            summary: "Creates an issue or a sub-task from a JSON representation"
            operationId: "createIssue"
            tags:
              - jira 
            security:
              - crowdAuth: []
            consumes:
            - "application/json"
            produces:
            - "application/json"
            parameters:
            - name: "updateHistory"
              in: "query"
              description: "if true then the user's project history is updated"
              type: "boolean"
              required: false
              default: false
            - name: "issue"
              in: "body"
              description: "The specification of the issue to create"
              schema:
                $ref: '#/definitions/JiraIssueCreationProperties'
            responses:
              201:
                description: "Returns a link to the created issue"
                schema:
                  $ref: '#/definitions/JiraCreatedIssue'
              400:
                description: "Returned if the input is invalid (e.g. missing required fields, invalid field values, and so forth)."

    /issue/{issueIdOrKey}/attachments:
        post:
            summary: "Add one or more attachments to an issue"
            operationId: "addAttachment"
            tags:
              - jira 
            security:
              - crowdAuth: []
            consumes:
            - "multipart/form-data"
            produces:
            - "application/json"
            parameters:
                - in: path
                  name: issueIdOrKey
                  type: string
                  required: true 
                - in: header
                  name: X-Atlassian-Token
                  type: string
                  required: false 
                  default: "no-check"
                - in: formData
                  name: file
                  type: file 
                  required: true
                  description: "The attachment to upload"
            responses:
                200:
                    description: "Upload of attachments was successful"
                403:
                    description: "Returned if attachments is disabled or if you don't have permission to add attachments to this issue."
                404:
                    description: "Returned if the requested issue is not found, the user does not have permission to view it, or if the attachments exceeds the maximum configured attachment size."
            

securityDefinitions:
    crowdAuth:
      type: basic

definitions:
    JiraCreatedIssue:
        type: "object"
        properties:
            id:
                type: "string"
            key:
                type: "string"
            self:
                type: "string"
    JiraIssueFieldsProject: # Needs to be completed
        type: "object"
        properties:
            id:
                type: "string"
    JiraIssueFieldsIssuetype:
        type: "object"
        properties:
            id:
                type: "string"
    JiraIssueFieldsAssignee:
        type: "object"
        properties:
            name:
                type: "string"
    JiraIssueFieldsReporter:
        type: "object"
        properties:
            name:
                type: "string"
    JiraIssueFieldsPriority:
        type: "object"
        properties:
            id:
                type: "string"
    JiraIssueFields: # Needs to be completed
        type: "object"
        properties:
            project:
                $ref: '#/definitions/JiraIssueFieldsProject'
            summary:
                type: "string"
            issuetype:
                $ref: '#/defintions/JiraIssueFieldsIssuetype'
            assignee:
                $ref: '#/defintions/JiraIssueFieldsAssignee'
            reporter:
                $ref: '#/defintions/JiraIssueFieldsReporter'
            priority:
                $ref: '#/defintions/JiraIssueFieldsPriority'
            labels:
                type: "array"
                items:
                    type: "string"
            description:
                type: "string"
    JiraIssueCreationProperties:
        type: "object"
        properties:
            fields:
                $ref: '#/definitions/JiraIssueFields'
            worklog:
                type: "object" # Needs to be implemented
