swagger: "2.0"
info:
    description: "This is the jira rest resources endpoint documentation"
    version: "8.4.0"
    title: "Jira Rest Resources"
basePath: "/api/2"
tags:
    - name: jira 
    
schemes: 
    - "https"
paths:
    /issue:
        post:
            summary: "Creates an issue or a sub-task from a JSON representation"
            operationId: "createIssue"
            tags:
              - jira 
            security:
              - crowdAuth: []
            consumes:
            - "application/json"
            produces:
            - "application/json"
            parameters:
            - name: "updateHistory"
              in: "query"
              description: "if true then the user's project history is updated"
              type: "boolean"
              required: false
              default: false
            - name: "issue"
              in: "body"
              description: "The specification of the issue to create"
              schema:
                $ref: '#/definitions/JiraIssueCreationProperties'
            responses:
              201:
                description: "Returns a link to the created issue"
                schema:
                  $ref: '#/definitions/JiraCreatedIssue'
              400:
                description: "Returned if the input is invalid (e.g. missing required fields, invalid field values, and so forth)."

securityDefinitions:
    crowdAuth:
      type: basic

definitions:
    JiraCreatedIssue:
        type: "object"
        properties:
            id:
                type: "string"
            key:
                type: "string"
            self:
                type: "string"
    JiraIssueFieldsProject: # Needs to be completed
        type: "object"
        properties:
            id:
                type: "string"
    JiraIssueFieldsIssuetype:
        type: "object"
        properties:
            id:
                type: "string"
    JiraIssueFieldsAssignee:
        type: "object"
        properties:
            name:
                type: "string"
    JiraIssueFieldsReporter:
        type: "object"
        properties:
            name:
                type: "string"
    JiraIssueFieldsPriority:
        type: "object"
        properties:
            id:
                type: "string"
    JiraIssueFields: # Needs to be completed
        type: "object"
        properties:
            project:
                $ref: '#/definitions/JiraIssueFieldsProject'
            summary:
                type: "string"
            issuetype:
                $ref: '#/defintions/JiraIssueFieldsIssuetype'
            assignee:
                $ref: '#/defintions/JiraIssueFieldsAssignee'
            reporter:
                $ref: '#/defintions/JiraIssueFieldsReporter'
            priority:
                $ref: '#/defintions/JiraIssueFieldsPriority'
            labels:
                type: "array"
                items:
                    type: "string"
            description:
                type: "string"
    JiraIssueCreationProperties:
        type: "object"
        properties:
            fields:
                $ref: '#/definitions/JiraIssueFields'
            worklog:
                type: "object" # Needs to be implemented
