<?php
/**
 * JiraIssueFieldsProjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  JiraClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jira Rest Resources
 *
 * This is the jira rest resources endpoint documentation
 *
 * The version of the OpenAPI document: 8.4.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JiraClient;

use PHPUnit\Framework\TestCase;

/**
 * JiraIssueFieldsProjectTest Class Doc Comment
 *
 * @category    Class
 * @description JiraIssueFieldsProject
 * @package     JiraClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class JiraIssueFieldsProjectTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "JiraIssueFieldsProject"
     */
    public function testJiraIssueFieldsProject()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
